# Generated by Django 4.0.4 on 2022-05-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.CharField(default='testing_default', max_length=400),
            preserve_default=False,
        ),
    ]
